# Generated by Django 5.2 on 2025-05-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Collection de galerie',
                'verbose_name_plural': 'Collections de galerie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/gallery/')),
            ],
            options={
                'verbose_name': 'Élément de galerie',
                'verbose_name_plural': 'Éléments de galerie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/collections/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gallery.gallerycollection')),
            ],
        ),
    ]
