# Generated by Django 5.2 on 2025-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheologyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('course_type', models.CharField(choices=[('online', 'Cours en ligne'), ('inperson', 'Cours en présentiel'), ('conference', 'Conférence'), ('seminar', 'Séminaire')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, help_text='Required for in-person courses', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='theology/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL', null=True)),
            ],
            options={
                'verbose_name': 'Cours de théologie',
                'verbose_name_plural': 'Cours de théologie',
                'ordering': ['-date'],
            },
        ),
    ]
