# Generated by Django 5.2 on 2025-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('cultes', 'Cultes'), ('evenements', 'Événements'), ('theologie', 'Cours de Théologie')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Section de la page d'accueil",
                'verbose_name_plural': "Sections de la page d'accueil",
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(help_text='e.g. Lausanne, Suisse', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service de la semaine',
                'verbose_name_plural': 'Services de la semaine',
                'ordering': ['-date'],
            },
        ),
    ]
