# Generated by Django 5.2 on 2025-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('theme', models.CharField(max_length=255)),
                ('expire_after_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('is_song', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description_main', models.TextField()),
                ('description_secondary', models.TextField(blank=True, null=True)),
                ('miniature', models.ImageField(upload_to='culte_thumbnails/')),
                ('is_song', models.BooleanField(default=False)),
                ('videos', models.ManyToManyField(blank=True, to='home.video')),
            ],
        ),
    ]
