# Generated by Django 5.2 on 2025-05-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_specialevent_video_culte'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='est_culte_de_la_semaine',
            field=models.BooleanField(default=False),
        ),
    ]
